package model;

public enum EventoCatan {

    // Turno inicial
    POBLADO_INICIAL_CONSTRUIDO,
    CARRETERA_INICIAL_CONSTRUIDA,
    CAMBIO_TURNO_INICIAL,
    FIN_TURNO_INICIAL,

    // Turno general
    DADOS_TIRADOS,
    RECURSOS_ENTREGADOS,
    POBLADO_CONSTRUIDO,
    CIUDAD_CONSTRUIDA,
    CARRETERA_CONSTRUIDA,
    LADRON_MOVIDO,
    JUGADOR_ROBADO,
    COMERCIO_CON_JUGADOR_REALIZADO,
    COMERCIO_CON_BANCO_REALIZADO,
    DESARROLLO_COMPRADO,
    CAMBIO_TURNO_GENERAL,

    // Fin de partida
    GANADOR
}