package model;

public enum EventoCatan {
    PREPARADO_DE_JUGADORES,
    CAMBIO_TURNO,
    SALIO_LADRON,
    JUGADORES_PREPARADOS_CON_NOMBRE,
    MOVER_LADRON,
    DESCARTAR_CARTAS,
    PRODUCCION,
    PUNTOS_CAMBIADOS,
    GANADOR
}